package oracle.sql;
public class ZONEIDMAP
{
/*  62 */   private static TableClass zoneid = new TableClass(544, 0.99F);
  
  protected static final int INV_ZONEID = -1;
  
  static
  {
/*  72 */     zoneid.put("Africa/Abidjan", Integer.valueOf(42));
/*  73 */     zoneid.put("Africa/Accra", Integer.valueOf(50));
/*  74 */     zoneid.put("Africa/Addis_Ababa", Integer.valueOf(47));
/*  75 */     zoneid.put("Africa/Algiers", Integer.valueOf(30));
/*  76 */     zoneid.put("Africa/Asmara", Integer.valueOf(46));
/*  77 */     zoneid.put("Africa/Asmera", Integer.valueOf(558));
/*  78 */     zoneid.put("Africa/Bamako", Integer.valueOf(58));
/*  79 */     zoneid.put("Africa/Bangui", Integer.valueOf(37));
/*  80 */     zoneid.put("Africa/Banjul", Integer.valueOf(49));
/*  81 */     zoneid.put("Africa/Bissau", Integer.valueOf(52));
/*  82 */     zoneid.put("Africa/Blantyre", Integer.valueOf(57));
/*  83 */     zoneid.put("Africa/Brazzaville", Integer.valueOf(41));
/*  84 */     zoneid.put("Africa/Bujumbura", Integer.valueOf(35));
/*  85 */     zoneid.put("Africa/Cairo", Integer.valueOf(44));
/*  86 */     zoneid.put("Africa/Casablanca", Integer.valueOf(61));
/*  87 */     zoneid.put("Africa/Conakry", Integer.valueOf(51));
/*  88 */     zoneid.put("Africa/Dakar", Integer.valueOf(69));
/*  89 */     zoneid.put("Africa/Dar_es_Salaam", Integer.valueOf(75));
/*  90 */     zoneid.put("Africa/Djibouti", Integer.valueOf(43));
/*  91 */     zoneid.put("Africa/Douala", Integer.valueOf(36));
/*  92 */     zoneid.put("Africa/El_Aaiun", Integer.valueOf(62));
/*  93 */     zoneid.put("Africa/Freetown", Integer.valueOf(70));
/*  94 */     zoneid.put("Africa/Gaborone", Integer.valueOf(33));
/*  95 */     zoneid.put("Africa/Harare", Integer.valueOf(80));
/*  96 */     zoneid.put("Africa/Johannesburg", Integer.valueOf(72));
/*  97 */     zoneid.put("Africa/Juba", Integer.valueOf(321));
/*  98 */     zoneid.put("Africa/Kampala", Integer.valueOf(78));
/*  99 */     zoneid.put("Africa/Khartoum", Integer.valueOf(73));
/* 100 */     zoneid.put("Africa/Kigali", Integer.valueOf(67));
/* 101 */     zoneid.put("Africa/Kinshasa", Integer.valueOf(39));
/* 102 */     zoneid.put("Africa/Lagos", Integer.valueOf(66));
/* 103 */     zoneid.put("Africa/Libreville", Integer.valueOf(48));
/* 104 */     zoneid.put("Africa/Lome", Integer.valueOf(76));
/* 105 */     zoneid.put("Africa/Luanda", Integer.valueOf(31));
/* 106 */     zoneid.put("Africa/Lubumbashi", Integer.valueOf(40));
/* 107 */     zoneid.put("Africa/Lusaka", Integer.valueOf(79));
/* 108 */     zoneid.put("Africa/Malabo", Integer.valueOf(45));
/* 109 */     zoneid.put("Africa/Maputo", Integer.valueOf(63));
/* 110 */     zoneid.put("Africa/Maseru", Integer.valueOf(54));
/* 111 */     zoneid.put("Africa/Mbabane", Integer.valueOf(74));
/* 112 */     zoneid.put("Africa/Mogadishu", Integer.valueOf(71));
/* 113 */     zoneid.put("Africa/Monrovia", Integer.valueOf(55));
/* 114 */     zoneid.put("Africa/Nairobi", Integer.valueOf(53));
/* 115 */     zoneid.put("Africa/Ndjamena", Integer.valueOf(38));
/* 116 */     zoneid.put("Africa/Niamey", Integer.valueOf(65));
/* 117 */     zoneid.put("Africa/Nouakchott", Integer.valueOf(60));
/* 118 */     zoneid.put("Africa/Ouagadougou", Integer.valueOf(34));
/* 119 */     zoneid.put("Africa/Porto-Novo", Integer.valueOf(32));
/* 120 */     zoneid.put("Africa/Sao_Tome", Integer.valueOf(68));
/* 121 */     zoneid.put("Africa/Timbuktu", Integer.valueOf(570));
/* 122 */     zoneid.put("Africa/Tripoli", Integer.valueOf(56));
/* 123 */     zoneid.put("Africa/Tunis", Integer.valueOf(77));
/* 124 */     zoneid.put("Africa/Windhoek", Integer.valueOf(64));
    
/* 128 */     zoneid.put("America/Adak", Integer.valueOf(108));
/* 129 */     zoneid.put("America/Anchorage", Integer.valueOf(106));
/* 130 */     zoneid.put("America/Anguilla", Integer.valueOf(146));
/* 131 */     zoneid.put("America/Antigua", Integer.valueOf(147));
/* 132 */     zoneid.put("America/Aruba", Integer.valueOf(181));
/* 133 */     zoneid.put("America/Asuncion", Integer.valueOf(200));
/* 134 */     zoneid.put("America/Bahia", Integer.valueOf(90));
/* 135 */     zoneid.put("America/Bahia_Banderas", Integer.valueOf(95));
/* 136 */     zoneid.put("America/Barbados", Integer.valueOf(149));
/* 137 */     zoneid.put("America/Belize", Integer.valueOf(150));
/* 138 */     zoneid.put("America/Bogota", Integer.valueOf(195));
/* 139 */     zoneid.put("America/Buenos_Aires", Integer.valueOf(175));
/* 140 */     zoneid.put("America/Argentina/Buenos_Aires", Integer.valueOf(687));
/* 141 */     zoneid.put("America/Argentina/Catamarca", Integer.valueOf(691));
/* 142 */     zoneid.put("America/Argentina/ComodRivadavia", Integer.valueOf(1203));
/* 143 */     zoneid.put("America/Argentina/Cordoba", Integer.valueOf(689));
/* 144 */     zoneid.put("America/Argentina/Jujuy", Integer.valueOf(690));
/* 145 */     zoneid.put("America/Argentina/La_Rioja", Integer.valueOf(99));
/* 146 */     zoneid.put("America/Argentina/Mendoza", Integer.valueOf(692));
/* 147 */     zoneid.put("America/Argentina/Rio_Gallegos", Integer.valueOf(98));
/* 148 */     zoneid.put("America/Argentina/Salta", Integer.valueOf(237));
/* 149 */     zoneid.put("America/Argentina/San_Juan", Integer.valueOf(229));
/* 150 */     zoneid.put("America/Argentina/San_Luis", Integer.valueOf(97));
/* 151 */     zoneid.put("America/Argentina/Tucuman", Integer.valueOf(228));
/* 152 */     zoneid.put("America/Argentina/Ushuaia", Integer.valueOf(176));
/* 153 */     zoneid.put("America/Atikokan", Integer.valueOf(221));
/* 154 */     zoneid.put("America/Blanc-Sablon", Integer.valueOf(224));
/* 155 */     zoneid.put("America/Campo_Grande", Integer.valueOf(222));
/* 156 */     zoneid.put("America/Caracas", Integer.valueOf(205));
/* 157 */     zoneid.put("America/Cayenne", Integer.valueOf(198));
/* 158 */     zoneid.put("America/Cayman", Integer.valueOf(151));
/* 159 */     zoneid.put("America/Chicago", Integer.valueOf(101));
/* 160 */     zoneid.put("America/Coral_Harbour", Integer.valueOf(733));
/* 161 */     zoneid.put("America/Costa_Rica", Integer.valueOf(152));
/* 162 */     zoneid.put("America/Cuiaba", Integer.valueOf(189));
/* 163 */     zoneid.put("America/Curacao", Integer.valueOf(196));
/* 164 */     zoneid.put("America/Danmarkshavn", Integer.valueOf(223));
/* 165 */     zoneid.put("America/Dawson_Creek", Integer.valueOf(131));
/* 166 */     zoneid.put("America/Denver", Integer.valueOf(102));
/* 167 */     zoneid.put("America/Dominica", Integer.valueOf(154));
/* 168 */     zoneid.put("America/Edmonton", Integer.valueOf(129));
/* 169 */     zoneid.put("America/Eirunepe", Integer.valueOf(225));
/* 170 */     zoneid.put("America/El_Salvador", Integer.valueOf(156));
/* 171 */     zoneid.put("America/Fortaleza", Integer.valueOf(185));
/* 172 */     zoneid.put("America/Glace_Bay", Integer.valueOf(121));
/* 173 */     zoneid.put("America/Godthab", Integer.valueOf(207));
/* 174 */     zoneid.put("America/Grand_Turk", Integer.valueOf(172));
/* 175 */     zoneid.put("America/Grenada", Integer.valueOf(157));
/* 176 */     zoneid.put("America/Guadeloupe", Integer.valueOf(158));
/* 177 */     zoneid.put("America/Guatemala", Integer.valueOf(159));
/* 178 */     zoneid.put("America/Guayaquil", Integer.valueOf(197));
/* 179 */     zoneid.put("America/Guyana", Integer.valueOf(199));
/* 180 */     zoneid.put("America/Halifax", Integer.valueOf(120));
/* 181 */     zoneid.put("America/Havana", Integer.valueOf(153));
/* 182 */     zoneid.put("America/Indiana/Knox", Integer.valueOf(113));
/* 183 */     zoneid.put("America/Indiana/Tell_City", Integer.valueOf(94));
/* 184 */     zoneid.put("America/Indiana/Winamac", Integer.valueOf(218));
/* 185 */     zoneid.put("America/Indianapolis", Integer.valueOf(111));
/* 186 */     zoneid.put("America/Jamaica", Integer.valueOf(162));
/* 187 */     zoneid.put("America/Jujuy", Integer.valueOf(178));
/* 188 */     zoneid.put("America/Kentucky/Louisville", Integer.valueOf(627));
/* 189 */     zoneid.put("America/Kentucky/Monticello", Integer.valueOf(91));
/* 190 */     zoneid.put("America/Kralendijk", Integer.valueOf(323));
/* 191 */     zoneid.put("America/La_Paz", Integer.valueOf(182));
/* 192 */     zoneid.put("America/Lima", Integer.valueOf(201));
/* 193 */     zoneid.put("America/Los_Angeles", Integer.valueOf(103));
/* 194 */     zoneid.put("America/Lower_Princes", Integer.valueOf(322));
/* 195 */     zoneid.put("America/Managua", Integer.valueOf(165));
/* 196 */     zoneid.put("America/Manaus", Integer.valueOf(192));
/* 197 */     zoneid.put("America/Marigot", Integer.valueOf(670));
/* 198 */     zoneid.put("America/Martinique", Integer.valueOf(163));
/* 199 */     zoneid.put("America/Matamoros", Integer.valueOf(87));
/* 200 */     zoneid.put("America/Mazatlan", Integer.valueOf(144));
/* 201 */     zoneid.put("America/Mendoza", Integer.valueOf(180));
/* 202 */     zoneid.put("America/Menominee", Integer.valueOf(117));
/* 203 */     zoneid.put("America/Merida", Integer.valueOf(226));
/* 204 */     zoneid.put("America/Metlakatla", Integer.valueOf(319));
/* 205 */     zoneid.put("America/Mexico_City", Integer.valueOf(141));
/* 206 */     zoneid.put("America/Miquelon", Integer.valueOf(170));
/* 207 */     zoneid.put("America/Moncton", Integer.valueOf(92));
/* 208 */     zoneid.put("America/Monterrey", Integer.valueOf(227));
/* 209 */     zoneid.put("America/Montevideo", Integer.valueOf(204));
/* 210 */     zoneid.put("America/Montreal", Integer.valueOf(122));
/* 211 */     zoneid.put("America/Montserrat", Integer.valueOf(164));
/* 212 */     zoneid.put("America/Nassau", Integer.valueOf(148));
/* 213 */     zoneid.put("America/New_York", Integer.valueOf(100));
/* 214 */     zoneid.put("America/Nipigon", Integer.valueOf(124));
/* 215 */     zoneid.put("America/Noronha", Integer.valueOf(183));
/* 216 */     zoneid.put("America/North_Dakota/Beulah", Integer.valueOf(320));
/* 217 */     zoneid.put("America/North_Dakota/Center", Integer.valueOf(88));
/* 218 */     zoneid.put("America/North_Dakota/New_Salem", Integer.valueOf(89));
/* 219 */     zoneid.put("America/Ojinaga", Integer.valueOf(93));
/* 220 */     zoneid.put("America/Panama", Integer.valueOf(166));
/* 221 */     zoneid.put("America/Pangnirtung", Integer.valueOf(132));
/* 222 */     zoneid.put("America/Paramaribo", Integer.valueOf(202));
/* 223 */     zoneid.put("America/Phoenix", Integer.valueOf(109));
/* 224 */     zoneid.put("America/Port-au-Prince", Integer.valueOf(160));
/* 225 */     zoneid.put("America/Port_of_Spain", Integer.valueOf(203));
/* 226 */     zoneid.put("America/Porto_Acre", Integer.valueOf(193));
/* 227 */     zoneid.put("America/Puerto_Rico", Integer.valueOf(167));
/* 228 */     zoneid.put("America/Rainy_River", Integer.valueOf(125));
/* 229 */     zoneid.put("America/Rankin_Inlet", Integer.valueOf(134));
/* 230 */     zoneid.put("America/Recife", Integer.valueOf(86));
/* 231 */     zoneid.put("America/Regina", Integer.valueOf(127));
/* 232 */     zoneid.put("America/Resolute", Integer.valueOf(219));
/* 233 */     zoneid.put("America/Rio_Branco", Integer.valueOf(1217));
/* 234 */     zoneid.put("America/Rosario", Integer.valueOf(1201));
/* 235 */     zoneid.put("America/Santiago", Integer.valueOf(194));
/* 236 */     zoneid.put("America/Santo_Domingo", Integer.valueOf(155));
/* 237 */     zoneid.put("America/Santa_Isabel", Integer.valueOf(96));
/* 238 */     zoneid.put("America/Sao_Paulo", Integer.valueOf(188));
/* 239 */     zoneid.put("America/Scoresbysund", Integer.valueOf(206));
/* 240 */     zoneid.put("America/Sitka", Integer.valueOf(318));
/* 241 */     zoneid.put("America/St_Barthelemy", Integer.valueOf(1182));
/* 242 */     zoneid.put("America/St_Johns", Integer.valueOf(118));
/* 243 */     zoneid.put("America/St_Kitts", Integer.valueOf(168));
/* 244 */     zoneid.put("America/St_Lucia", Integer.valueOf(169));
/* 245 */     zoneid.put("America/St_Thomas", Integer.valueOf(174));
/* 246 */     zoneid.put("America/St_Vincent", Integer.valueOf(171));
/* 247 */     zoneid.put("America/Tegucigalpa", Integer.valueOf(161));
/* 248 */     zoneid.put("America/Thule", Integer.valueOf(208));
/* 249 */     zoneid.put("America/Tijuana", Integer.valueOf(145));
/* 250 */     zoneid.put("America/Toronto", Integer.valueOf(220));
/* 251 */     zoneid.put("America/Tortola", Integer.valueOf(173));
/* 252 */     zoneid.put("America/Vancouver", Integer.valueOf(130));
/* 253 */     zoneid.put("America/Winnipeg", Integer.valueOf(126));
/* 254 */     zoneid.put("America/Yakutat", Integer.valueOf(105));
/* 255 */     zoneid.put("PST", Integer.valueOf(2151));
/* 256 */     zoneid.put("EST", Integer.valueOf(211));
/* 257 */     zoneid.put("CST", Integer.valueOf(1637));
    
/* 260 */     zoneid.put("Arctic/Longyearbyen", Integer.valueOf(909));
    
/* 263 */     zoneid.put("Antarctica/Casey", Integer.valueOf(230));
/* 264 */     zoneid.put("Antarctica/Davis", Integer.valueOf(231));
/* 265 */     zoneid.put("Antarctica/DumontDUrville", Integer.valueOf(233));
/* 266 */     zoneid.put("Antarctica/Mawson", Integer.valueOf(232));
/* 267 */     zoneid.put("Antarctica/McMurdo", Integer.valueOf(236));
/* 268 */     zoneid.put("Antarctica/Macquarie", Integer.valueOf(85));
/* 269 */     zoneid.put("Antarctica/Palmer", Integer.valueOf(235));
/* 270 */     zoneid.put("Antarctica/South_Pole", Integer.valueOf(748));
/* 271 */     zoneid.put("Antarctica/Syowa", Integer.valueOf(234));
    
/* 274 */     zoneid.put("Asia/Aden", Integer.valueOf(302));
/* 275 */     zoneid.put("Asia/Amman", Integer.valueOf(268));
/* 276 */     zoneid.put("Asia/Anadyr", Integer.valueOf(312));
/* 277 */     zoneid.put("Asia/Aqtau", Integer.valueOf(271));
/* 278 */     zoneid.put("Asia/Aqtobe", Integer.valueOf(270));
/* 279 */     zoneid.put("Asia/Ashgabat", Integer.valueOf(297));
/* 280 */     zoneid.put("Asia/Ashkhabad", Integer.valueOf(809));
/* 281 */     zoneid.put("Asia/Baghdad", Integer.valueOf(265));
/* 282 */     zoneid.put("Asia/Bahrain", Integer.valueOf(243));
/* 283 */     zoneid.put("Asia/Baku", Integer.valueOf(242));
/* 284 */     zoneid.put("Asia/Bangkok", Integer.valueOf(296));
/* 285 */     zoneid.put("Asia/Beirut", Integer.valueOf(277));
/* 286 */     zoneid.put("Asia/Bishkek", Integer.valueOf(272));
/* 287 */     zoneid.put("Asia/Brunei", Integer.valueOf(246));
/* 288 */     zoneid.put("Asia/Calcutta", Integer.valueOf(260));
/* 289 */     zoneid.put("Asia/Choibalsan", Integer.valueOf(316));
/* 290 */     zoneid.put("Asia/Chongqing", Integer.valueOf(763));
/* 291 */     zoneid.put("Asia/Colombo", Integer.valueOf(293));
/* 292 */     zoneid.put("Asia/Dacca", Integer.valueOf(244));
/* 293 */     zoneid.put("Asia/Damascus", Integer.valueOf(294));
/* 294 */     zoneid.put("Asia/Dhaka", Integer.valueOf(756));
/* 295 */     zoneid.put("Asia/Dili", Integer.valueOf(259));
/* 296 */     zoneid.put("Asia/Dubai", Integer.valueOf(298));
/* 297 */     zoneid.put("Asia/Dushanbe", Integer.valueOf(295));
/* 298 */     zoneid.put("Asia/Ho_Chi_Minh", Integer.valueOf(813));
/* 299 */     zoneid.put("Asia/Hong_Kong", Integer.valueOf(254));
/* 300 */     zoneid.put("Asia/Hovd", Integer.valueOf(280));
/* 301 */     zoneid.put("Asia/Irkutsk", Integer.valueOf(307));
/* 302 */     zoneid.put("Asia/Jakarta", Integer.valueOf(261));
/* 303 */     zoneid.put("Asia/Jayapura", Integer.valueOf(263));
/* 304 */     zoneid.put("Asia/Jerusalem", Integer.valueOf(266));
/* 305 */     zoneid.put("Asia/Kabul", Integer.valueOf(240));
/* 306 */     zoneid.put("Asia/Kamchatka", Integer.valueOf(311));
/* 307 */     zoneid.put("Asia/Karachi", Integer.valueOf(284));
/* 308 */     zoneid.put("Asia/Katmandu", Integer.valueOf(282));
/* 309 */     zoneid.put("Asia/Kathmandu", Integer.valueOf(797));
/* 310 */     zoneid.put("Asia/Kolkata", Integer.valueOf(772));
/* 311 */     zoneid.put("Asia/Krasnoyarsk", Integer.valueOf(306));
/* 312 */     zoneid.put("Asia/Kuala_Lumpur", Integer.valueOf(278));
/* 313 */     zoneid.put("Asia/Kuwait", Integer.valueOf(275));
/* 314 */     zoneid.put("Asia/Macao", Integer.valueOf(256));
/* 315 */     zoneid.put("Asia/Macau", Integer.valueOf(768));
/* 316 */     zoneid.put("Asia/Magadan", Integer.valueOf(310));
/* 317 */     zoneid.put("Asia/Makassar", Integer.valueOf(774));
/* 318 */     zoneid.put("Asia/Manila", Integer.valueOf(286));
/* 319 */     zoneid.put("Asia/Muscat", Integer.valueOf(283));
/* 320 */     zoneid.put("Asia/Nicosia", Integer.valueOf(257));
/* 321 */     zoneid.put("Asia/Novosibirsk", Integer.valueOf(305));
/* 322 */     zoneid.put("Asia/Oral", Integer.valueOf(315));
/* 323 */     zoneid.put("Asia/Phnom_Penh", Integer.valueOf(248));
/* 324 */     zoneid.put("Asia/Pontianak", Integer.valueOf(313));
/* 325 */     zoneid.put("Asia/Pyongyang", Integer.valueOf(274));
/* 326 */     zoneid.put("Asia/Qatar", Integer.valueOf(287));
/* 327 */     zoneid.put("Asia/Qyzylorda", Integer.valueOf(314));
/* 328 */     zoneid.put("Asia/Rangoon", Integer.valueOf(247));
/* 329 */     zoneid.put("Asia/Riyadh", Integer.valueOf(288));
/* 330 */     zoneid.put("Asia/Saigon", Integer.valueOf(301));
/* 331 */     zoneid.put("Asia/Sakhalin", Integer.valueOf(317));
/* 332 */     zoneid.put("Asia/Seoul", Integer.valueOf(273));
/* 333 */     zoneid.put("Asia/Samarkand", Integer.valueOf(299));
/* 334 */     zoneid.put("Asia/Shanghai", Integer.valueOf(250));
/* 335 */     zoneid.put("Asia/Singapore", Integer.valueOf(292));
/* 336 */     zoneid.put("Asia/Taipei", Integer.valueOf(255));
/* 337 */     zoneid.put("Asia/Tashkent", Integer.valueOf(300));
/* 338 */     zoneid.put("Asia/Tbilisi", Integer.valueOf(258));
/* 339 */     zoneid.put("Asia/Tehran", Integer.valueOf(264));
/* 340 */     zoneid.put("Asia/Thimbu", Integer.valueOf(757));
/* 341 */     zoneid.put("Asia/Thimphu", Integer.valueOf(245));
/* 342 */     zoneid.put("Asia/Tokyo", Integer.valueOf(267));
/* 343 */     zoneid.put("Asia/Ujung_Pandang", Integer.valueOf(262));
/* 344 */     zoneid.put("Asia/Ulaanbaatar", Integer.valueOf(281));
/* 345 */     zoneid.put("Asia/Ulan_Bator", Integer.valueOf(793));
/* 346 */     zoneid.put("Asia/Vientiane", Integer.valueOf(276));
/* 347 */     zoneid.put("Asia/Vladivostok", Integer.valueOf(309));
/* 348 */     zoneid.put("Asia/Yakutsk", Integer.valueOf(308));
/* 349 */     zoneid.put("Asia/Yekaterinburg", Integer.valueOf(303));
/* 350 */     zoneid.put("Asia/Yerevan", Integer.valueOf(241));
    
/* 354 */     zoneid.put("Atlantic/Azores", Integer.valueOf(336));
/* 355 */     zoneid.put("Atlantic/Bermuda", Integer.valueOf(330));
/* 356 */     zoneid.put("Atlantic/Canary", Integer.valueOf(338));
/* 357 */     zoneid.put("Atlantic/Cape_Verde", Integer.valueOf(339));
/* 358 */     zoneid.put("Atlantic/Faeroe", Integer.valueOf(845));
/* 359 */     zoneid.put("Atlantic/Faroe", Integer.valueOf(333));
/* 360 */     zoneid.put("Atlantic/Jan_Mayen", Integer.valueOf(1421));
/* 361 */     zoneid.put("Atlantic/Reykjavik", Integer.valueOf(334));
/* 362 */     zoneid.put("Atlantic/South_Georgia", Integer.valueOf(332));
/* 363 */     zoneid.put("Atlantic/St_Helena", Integer.valueOf(340));
/* 364 */     zoneid.put("Atlantic/Stanley", Integer.valueOf(331));
    
/* 368 */     zoneid.put("Australia/Adelaide", Integer.valueOf(349));
/* 369 */     zoneid.put("Australia/Brisbane", Integer.valueOf(347));
/* 370 */     zoneid.put("Australia/Currie", Integer.valueOf(355));
/* 371 */     zoneid.put("Australia/Darwin", Integer.valueOf(345));
/* 372 */     zoneid.put("Australia/Eucla", Integer.valueOf(356));
/* 373 */     zoneid.put("Australia/Perth", Integer.valueOf(346));
/* 374 */     zoneid.put("Australia/Sydney", Integer.valueOf(352));
/* 375 */     zoneid.put("Australia/ACT", Integer.valueOf(864));
    
/* 379 */     zoneid.put("EET", Integer.valueOf(368));
/* 380 */     zoneid.put("GMT", Integer.valueOf(513));
/* 381 */     zoneid.put("UTC", Integer.valueOf(5121));
/* 382 */     zoneid.put("MET", Integer.valueOf(367));
/* 383 */     zoneid.put("MST", Integer.valueOf(212));
/* 384 */     zoneid.put("HST", Integer.valueOf(213));
    
/* 387 */     zoneid.put("Europe/Amsterdam", Integer.valueOf(396));
/* 388 */     zoneid.put("Europe/Andorra", Integer.valueOf(373));
/* 389 */     zoneid.put("Europe/Athens", Integer.valueOf(385));
/* 390 */     zoneid.put("Europe/Belgrade", Integer.valueOf(412));
/* 391 */     zoneid.put("Europe/Berlin", Integer.valueOf(383));
/* 392 */     zoneid.put("Europe/Brussels", Integer.valueOf(376));
/* 393 */     zoneid.put("Europe/Bucharest", Integer.valueOf(400));
/* 394 */     zoneid.put("Europe/Budapest", Integer.valueOf(386));
/* 395 */     zoneid.put("Europe/Chisinau", Integer.valueOf(393));
/* 396 */     zoneid.put("Europe/Copenhagen", Integer.valueOf(379));
/* 397 */     zoneid.put("Europe/Dublin", Integer.valueOf(371));
/* 398 */     zoneid.put("Europe/Gibraltar", Integer.valueOf(384));
/* 399 */     zoneid.put("Europe/Guernsey", Integer.valueOf(2417));
/* 400 */     zoneid.put("Europe/Helsinki", Integer.valueOf(381));
/* 401 */     zoneid.put("Europe/Isle_of_Man", Integer.valueOf(2929));
/* 402 */     zoneid.put("Europe/Istanbul", Integer.valueOf(407));
/* 403 */     zoneid.put("Europe/Jersey", Integer.valueOf(1905));
/* 404 */     zoneid.put("Europe/Kaliningrad", Integer.valueOf(401));
/* 405 */     zoneid.put("Europe/Kiev", Integer.valueOf(408));
/* 406 */     zoneid.put("Europe/Lisbon", Integer.valueOf(399));
/* 407 */     zoneid.put("Europe/London", Integer.valueOf(369));
/* 408 */     zoneid.put("Europe/Luxembourg", Integer.valueOf(391));
/* 409 */     zoneid.put("Europe/Madrid", Integer.valueOf(404));
/* 410 */     zoneid.put("Europe/Malta", Integer.valueOf(392));
/* 411 */     zoneid.put("Europe/Mariehamn", Integer.valueOf(893));
/* 412 */     zoneid.put("Europe/Minsk", Integer.valueOf(375));
/* 413 */     zoneid.put("Europe/Monaco", Integer.valueOf(395));
/* 414 */     zoneid.put("Europe/Moscow", Integer.valueOf(402));
/* 415 */     zoneid.put("Europe/Nicosia", Integer.valueOf(769));
/* 416 */     zoneid.put("Europe/Oslo", Integer.valueOf(397));
/* 417 */     zoneid.put("Europe/Paris", Integer.valueOf(382));
/* 418 */     zoneid.put("Europe/Podgorica", Integer.valueOf(2972));
/* 419 */     zoneid.put("Europe/Prague", Integer.valueOf(378));
/* 420 */     zoneid.put("Europe/Riga", Integer.valueOf(388));
/* 421 */     zoneid.put("Europe/Rome", Integer.valueOf(387));
/* 422 */     zoneid.put("Europe/Samara", Integer.valueOf(403));
/* 423 */     zoneid.put("Europe/Simferopol", Integer.valueOf(411));
/* 424 */     zoneid.put("Europe/Sofia", Integer.valueOf(377));
/* 425 */     zoneid.put("Europe/Stockholm", Integer.valueOf(405));
/* 426 */     zoneid.put("Europe/Tallinn", Integer.valueOf(380));
/* 427 */     zoneid.put("Europe/Tirane", Integer.valueOf(372));
/* 428 */     zoneid.put("Europe/Tiraspol", Integer.valueOf(905));
/* 429 */     zoneid.put("Europe/Vaduz", Integer.valueOf(389));
/* 430 */     zoneid.put("Europe/Vienna", Integer.valueOf(374));
/* 431 */     zoneid.put("Europe/Vilnius", Integer.valueOf(390));
/* 432 */     zoneid.put("Europe/Volgograd", Integer.valueOf(413));
/* 433 */     zoneid.put("Europe/Warsaw", Integer.valueOf(398));
/* 434 */     zoneid.put("Europe/Zurich", Integer.valueOf(406));
    
/* 438 */     zoneid.put("Indian/Antananarivo", Integer.valueOf(438));
/* 439 */     zoneid.put("Indian/Chagos", Integer.valueOf(436));
/* 440 */     zoneid.put("Indian/Christmas", Integer.valueOf(439));
/* 441 */     zoneid.put("Indian/Cocos", Integer.valueOf(440));
/* 442 */     zoneid.put("Indian/Comoro", Integer.valueOf(441));
/* 443 */     zoneid.put("Indian/Kerguelen", Integer.valueOf(435));
/* 444 */     zoneid.put("Indian/Mahe", Integer.valueOf(442));
/* 445 */     zoneid.put("Indian/Maldives", Integer.valueOf(437));
/* 446 */     zoneid.put("Indian/Mauritius", Integer.valueOf(443));
/* 447 */     zoneid.put("Indian/Mayotte", Integer.valueOf(444));
/* 448 */     zoneid.put("Indian/Reunion", Integer.valueOf(445));
    
/* 453 */     zoneid.put("Pacific/Apia", Integer.valueOf(479));
/* 454 */     zoneid.put("Pacific/Auckland", Integer.valueOf(471));
/* 455 */     zoneid.put("Pacific/Chatham", Integer.valueOf(472));
/* 456 */     zoneid.put("Pacific/Chuuk", Integer.valueOf(238));
/* 457 */     zoneid.put("Pacific/Easter", Integer.valueOf(451));
/* 458 */     zoneid.put("Pacific/Efate", Integer.valueOf(488));
/* 459 */     zoneid.put("Pacific/Enderbury", Integer.valueOf(460));
/* 460 */     zoneid.put("Pacific/Fakaofo", Integer.valueOf(482));
/* 461 */     zoneid.put("Pacific/Fiji", Integer.valueOf(454));
/* 462 */     zoneid.put("Pacific/Funafuti", Integer.valueOf(484));
/* 463 */     zoneid.put("Pacific/Galapagos", Integer.valueOf(452));
/* 464 */     zoneid.put("Pacific/Gambier", Integer.valueOf(455));
/* 465 */     zoneid.put("Pacific/Guadalcanal", Integer.valueOf(481));
/* 466 */     zoneid.put("Pacific/Guam", Integer.valueOf(458));
/* 467 */     zoneid.put("Pacific/Honolulu", Integer.valueOf(450));
/* 468 */     zoneid.put("Pacific/Kiritimati", Integer.valueOf(461));
/* 469 */     zoneid.put("Pacific/Kosrae", Integer.valueOf(468));
/* 470 */     zoneid.put("Pacific/Majuro", Integer.valueOf(463));
/* 471 */     zoneid.put("Pacific/Marquesas", Integer.valueOf(456));
/* 472 */     zoneid.put("Pacific/Nauru", Integer.valueOf(469));
/* 473 */     zoneid.put("Pacific/Niue", Integer.valueOf(473));
/* 474 */     zoneid.put("Pacific/Norfolk", Integer.valueOf(474));
/* 475 */     zoneid.put("Pacific/Noumea", Integer.valueOf(470));
/* 476 */     zoneid.put("Pacific/Pago_Pago", Integer.valueOf(478));
/* 477 */     zoneid.put("Pacific/Palau", Integer.valueOf(475));
/* 478 */     zoneid.put("Pacific/Pitcairn", Integer.valueOf(477));
/* 479 */     zoneid.put("Pacific/Pohnpei", Integer.valueOf(239));
/* 480 */     zoneid.put("Pacific/Ponape", Integer.valueOf(467));
/* 481 */     zoneid.put("Pacific/Port_Moresby", Integer.valueOf(476));
/* 482 */     zoneid.put("Pacific/Rarotonga", Integer.valueOf(453));
/* 483 */     zoneid.put("Pacific/Saipan", Integer.valueOf(462));
/* 484 */     zoneid.put("Pacific/Tahiti", Integer.valueOf(457));
/* 485 */     zoneid.put("Pacific/Tarawa", Integer.valueOf(459));
/* 486 */     zoneid.put("Pacific/Tongatapu", Integer.valueOf(483));
/* 487 */     zoneid.put("Pacific/Truk", Integer.valueOf(466));
/* 488 */     zoneid.put("Pacific/Wake", Integer.valueOf(487));
/* 489 */     zoneid.put("Pacific/Wallis", Integer.valueOf(489));
    
/* 498 */     zoneid.put("Egypt", Integer.valueOf(556));
/* 499 */     zoneid.put("Africa/Ceuta", Integer.valueOf(81));
/* 500 */     zoneid.put("Libya", Integer.valueOf(568));
/* 501 */     zoneid.put("America/Atka", Integer.valueOf(620));
/* 502 */     zoneid.put("US/Aleutian", Integer.valueOf(1132));
/* 503 */     zoneid.put("US/Alaska", Integer.valueOf(618));
/* 504 */     zoneid.put("America/Araguaina", Integer.valueOf(186));
/* 505 */     zoneid.put("America/Belem", Integer.valueOf(184));
/* 506 */     zoneid.put("America/Boa_Vista", Integer.valueOf(191));
/* 507 */     zoneid.put("America/Boise", Integer.valueOf(110));
/* 508 */     zoneid.put("America/Cambridge_Bay", Integer.valueOf(135));
/* 509 */     zoneid.put("America/Cancun", Integer.valueOf(140));
/* 510 */     zoneid.put("America/Catamarca", Integer.valueOf(179));
/* 511 */     zoneid.put("CST6CDT", Integer.valueOf(215));
/* 512 */     zoneid.put("US/Central", Integer.valueOf(613));
/* 513 */     zoneid.put("America/Chihuahua", Integer.valueOf(142));
/* 514 */     zoneid.put("America/Cordoba", Integer.valueOf(177));
/* 515 */     zoneid.put("America/Dawson", Integer.valueOf(139));
/* 516 */     zoneid.put("America/Shiprock", Integer.valueOf(1638));
/* 517 */     zoneid.put("MST7MDT", Integer.valueOf(216));
/* 518 */     zoneid.put("Navajo", Integer.valueOf(614));
/* 519 */     zoneid.put("US/Mountain", Integer.valueOf(1126));
/* 520 */     zoneid.put("America/Detroit", Integer.valueOf(116));
/* 521 */     zoneid.put("US/Michigan", Integer.valueOf(628));
/* 522 */     zoneid.put("Canada/Mountain", Integer.valueOf(641));
/* 523 */     zoneid.put("America/Goose_Bay", Integer.valueOf(119));
/* 524 */     zoneid.put("Canada/Atlantic", Integer.valueOf(632));
/* 525 */     zoneid.put("Cuba", Integer.valueOf(665));
/* 526 */     zoneid.put("America/Hermosillo", Integer.valueOf(143));
/* 527 */     zoneid.put("America/Knox_IN", Integer.valueOf(625));
/* 528 */     zoneid.put("US/Indiana-Starke", Integer.valueOf(1137));
/* 529 */     zoneid.put("America/Indiana/Marengo", Integer.valueOf(112));
/* 530 */     zoneid.put("America/Indiana/Vevay", Integer.valueOf(114));
/* 531 */     zoneid.put("America/Fort_Wayne", Integer.valueOf(623));
/* 532 */     zoneid.put("America/Indiana/Indianapolis", Integer.valueOf(1647));
/* 533 */     zoneid.put("America/Indiana/Vincennes", Integer.valueOf(209));
/* 534 */     zoneid.put("America/Indiana/Petersburg", Integer.valueOf(210));
/* 535 */     zoneid.put("US/East-Indiana", Integer.valueOf(1135));
/* 536 */     zoneid.put("America/Inuvik", Integer.valueOf(137));
/* 537 */     zoneid.put("America/Iqaluit", Integer.valueOf(133));
/* 538 */     zoneid.put("Jamaica", Integer.valueOf(674));
/* 539 */     zoneid.put("America/Juneau", Integer.valueOf(104));
/* 540 */     zoneid.put("PST8PDT", Integer.valueOf(217));
/* 541 */     zoneid.put("US/Pacific", Integer.valueOf(615));
/* 542 */     zoneid.put("US/Pacific-New", Integer.valueOf(1639));
/* 543 */     zoneid.put("America/Louisville", Integer.valueOf(115));
/* 544 */     zoneid.put("America/Maceio", Integer.valueOf(187));
/* 545 */     zoneid.put("Brazil/West", Integer.valueOf(704));
/* 546 */     zoneid.put("Mexico/BajaSur", Integer.valueOf(656));
/* 547 */     zoneid.put("Mexico/General", Integer.valueOf(653));
/* 548 */     zoneid.put("Canada/Eastern", Integer.valueOf(634));
/* 549 */     zoneid.put("EST5EDT", Integer.valueOf(214));
/* 550 */     zoneid.put("US/Eastern", Integer.valueOf(612));
/* 551 */     zoneid.put("America/Nome", Integer.valueOf(107));
/* 552 */     zoneid.put("Brazil/DeNoronha", Integer.valueOf(695));
/* 553 */     zoneid.put("US/Arizona", Integer.valueOf(621));
/* 554 */     zoneid.put("Brazil/Acre", Integer.valueOf(705));
/* 555 */     zoneid.put("America/Porto_Velho", Integer.valueOf(190));
/* 556 */     zoneid.put("Canada/East-Saskatchewan", Integer.valueOf(639));
/* 557 */     zoneid.put("Canada/Saskatchewan", Integer.valueOf(1151));
/* 558 */     zoneid.put("Chile/Continental", Integer.valueOf(706));
/* 559 */     zoneid.put("Brazil/East", Integer.valueOf(700));
/* 560 */     zoneid.put("Canada/Newfoundland", Integer.valueOf(630));
/* 561 */     zoneid.put("America/Virgin", Integer.valueOf(686));
/* 562 */     zoneid.put("America/Swift_Current", Integer.valueOf(128));
/* 563 */     zoneid.put("America/Thunder_Bay", Integer.valueOf(123));
/* 564 */     zoneid.put("America/Ensenada", Integer.valueOf(657));
/* 565 */     zoneid.put("Mexico/BajaNorte", Integer.valueOf(1169));
/* 566 */     zoneid.put("Canada/Pacific", Integer.valueOf(642));
/* 567 */     zoneid.put("America/Whitehorse", Integer.valueOf(138));
/* 568 */     zoneid.put("Canada/Yukon", Integer.valueOf(650));
/* 569 */     zoneid.put("Canada/Central", Integer.valueOf(638));
/* 570 */     zoneid.put("America/Yellowknife", Integer.valueOf(136));
/* 571 */     zoneid.put("Asia/Almaty", Integer.valueOf(269));
/* 572 */     zoneid.put("Asia/Chungking", Integer.valueOf(251));
/* 573 */     zoneid.put("Asia/Gaza", Integer.valueOf(285));
/* 574 */     zoneid.put("Asia/Harbin", Integer.valueOf(249));
/* 575 */     zoneid.put("Hongkong", Integer.valueOf(766));
/* 576 */     zoneid.put("Asia/Istanbul", Integer.valueOf(1431));
/* 577 */     zoneid.put("Asia/Tel_Aviv", Integer.valueOf(778));
/* 578 */     zoneid.put("Israel", Integer.valueOf(1290));
/* 579 */     zoneid.put("Asia/Kashgar", Integer.valueOf(253));
/* 580 */     zoneid.put("Asia/Kuching", Integer.valueOf(279));
/* 581 */     zoneid.put("Asia/Omsk", Integer.valueOf(304));
/* 582 */     zoneid.put("Asia/Riyadh87", Integer.valueOf(289));
/* 583 */     zoneid.put("Mideast/Riyadh87", Integer.valueOf(801));
/* 584 */     zoneid.put("Asia/Riyadh88", Integer.valueOf(290));
/* 585 */     zoneid.put("Mideast/Riyadh88", Integer.valueOf(802));
/* 586 */     zoneid.put("Asia/Riyadh89", Integer.valueOf(291));
/* 587 */     zoneid.put("Mideast/Riyadh89", Integer.valueOf(803));
/* 588 */     zoneid.put("ROK", Integer.valueOf(785));
/* 589 */     zoneid.put("PRC", Integer.valueOf(762));
/* 590 */     zoneid.put("Singapore", Integer.valueOf(804));
/* 591 */     zoneid.put("ROC", Integer.valueOf(767));
/* 592 */     zoneid.put("Iran", Integer.valueOf(776));
/* 593 */     zoneid.put("Japan", Integer.valueOf(779));
/* 594 */     zoneid.put("Asia/Urumqi", Integer.valueOf(252));
/* 595 */     zoneid.put("Atlantic/Madeira", Integer.valueOf(337));
/* 596 */     zoneid.put("Iceland", Integer.valueOf(846));
/* 597 */     zoneid.put("Australia/South", Integer.valueOf(861));
/* 598 */     zoneid.put("Australia/Queensland", Integer.valueOf(859));
/* 599 */     zoneid.put("Australia/Broken_Hill", Integer.valueOf(353));
/* 600 */     zoneid.put("Australia/Yancowinna", Integer.valueOf(865));
/* 601 */     zoneid.put("Australia/North", Integer.valueOf(857));
/* 602 */     zoneid.put("Australia/Hobart", Integer.valueOf(350));
/* 603 */     zoneid.put("Australia/Tasmania", Integer.valueOf(862));
/* 604 */     zoneid.put("Australia/Lindeman", Integer.valueOf(348));
/* 605 */     zoneid.put("Australia/Lord_Howe", Integer.valueOf(354));
/* 606 */     zoneid.put("Australia/LHI", Integer.valueOf(866));
/* 607 */     zoneid.put("Australia/Melbourne", Integer.valueOf(351));
/* 608 */     zoneid.put("Australia/Victoria", Integer.valueOf(863));
/* 609 */     zoneid.put("Australia/West", Integer.valueOf(858));
/* 610 */     zoneid.put("Australia/Canberra", Integer.valueOf(1376));
/* 611 */     zoneid.put("Australia/NSW", Integer.valueOf(1888));
/* 612 */     zoneid.put("CET", Integer.valueOf(366));
/* 613 */     zoneid.put("Etc/GMT", Integer.valueOf(1));
/* 614 */     zoneid.put("Etc/GMT+0", Integer.valueOf(1025));
/* 615 */     zoneid.put("Etc/GMT-0", Integer.valueOf(2049));
/* 616 */     zoneid.put("Etc/GMT0", Integer.valueOf(3073));
/* 617 */     zoneid.put("Etc/Greenwich", Integer.valueOf(4097));
/* 618 */     zoneid.put("GMT+0", Integer.valueOf(1537));
/* 619 */     zoneid.put("GMT-0", Integer.valueOf(2561));
/* 620 */     zoneid.put("GMT0", Integer.valueOf(3585));
/* 621 */     zoneid.put("Greenwich", Integer.valueOf(4609));
/* 622 */     zoneid.put("Etc/GMT+1", Integer.valueOf(16));
/* 623 */     zoneid.put("Etc/GMT+10", Integer.valueOf(25));
/* 624 */     zoneid.put("Etc/GMT+11", Integer.valueOf(26));
/* 625 */     zoneid.put("Etc/GMT+12", Integer.valueOf(27));
/* 626 */     zoneid.put("Etc/GMT+2", Integer.valueOf(17));
/* 627 */     zoneid.put("Etc/GMT+3", Integer.valueOf(18));
/* 628 */     zoneid.put("Etc/GMT+4", Integer.valueOf(19));
/* 629 */     zoneid.put("Etc/GMT+5", Integer.valueOf(20));
/* 630 */     zoneid.put("Etc/GMT+6", Integer.valueOf(21));
/* 631 */     zoneid.put("Etc/GMT+7", Integer.valueOf(22));
/* 632 */     zoneid.put("Etc/GMT+8", Integer.valueOf(23));
/* 633 */     zoneid.put("Etc/GMT+9", Integer.valueOf(24));
/* 634 */     zoneid.put("Etc/GMT-1", Integer.valueOf(15));
/* 635 */     zoneid.put("Etc/GMT-10", Integer.valueOf(6));
/* 636 */     zoneid.put("Etc/GMT-11", Integer.valueOf(5));
/* 637 */     zoneid.put("Etc/GMT-12", Integer.valueOf(4));
/* 638 */     zoneid.put("Etc/GMT-13", Integer.valueOf(3));
/* 639 */     zoneid.put("Etc/GMT-14", Integer.valueOf(2));
/* 640 */     zoneid.put("Etc/GMT-2", Integer.valueOf(14));
/* 641 */     zoneid.put("Etc/GMT-3", Integer.valueOf(13));
/* 642 */     zoneid.put("Etc/GMT-4", Integer.valueOf(12));
/* 643 */     zoneid.put("Etc/GMT-5", Integer.valueOf(11));
/* 644 */     zoneid.put("Etc/GMT-6", Integer.valueOf(10));
/* 645 */     zoneid.put("Etc/GMT-7", Integer.valueOf(9));
/* 646 */     zoneid.put("Etc/GMT-8", Integer.valueOf(8));
/* 647 */     zoneid.put("Etc/GMT-9", Integer.valueOf(7));
/* 648 */     zoneid.put("Europe/Belfast", Integer.valueOf(370));
/* 649 */     zoneid.put("Europe/Ljubljana", Integer.valueOf(924));
/* 650 */     zoneid.put("Europe/Sarajevo", Integer.valueOf(1436));
/* 651 */     zoneid.put("Europe/Skopje", Integer.valueOf(1948));
/* 652 */     zoneid.put("Europe/Zagreb", Integer.valueOf(2460));
/* 653 */     zoneid.put("Eire", Integer.valueOf(883));
/* 654 */     zoneid.put("Turkey", Integer.valueOf(919));
/* 655 */     zoneid.put("Portugal", Integer.valueOf(911));
/* 656 */     zoneid.put("GB", Integer.valueOf(881));
/* 657 */     zoneid.put("GB-Eire", Integer.valueOf(1393));
/* 658 */     zoneid.put("W-SU", Integer.valueOf(914));
/* 659 */     zoneid.put("Europe/Bratislava", Integer.valueOf(890));
/* 660 */     zoneid.put("Europe/San_Marino", Integer.valueOf(1411));
/* 661 */     zoneid.put("Europe/Vatican", Integer.valueOf(899));
/* 662 */     zoneid.put("Europe/Uzhgorod", Integer.valueOf(409));
/* 663 */     zoneid.put("Poland", Integer.valueOf(910));
/* 664 */     zoneid.put("Europe/Zaporozhye", Integer.valueOf(410));
/* 665 */     zoneid.put("NZ", Integer.valueOf(983));
/* 666 */     zoneid.put("NZ-CHAT", Integer.valueOf(984));
/* 667 */     zoneid.put("Chile/EasterIsland", Integer.valueOf(963));
/* 668 */     zoneid.put("US/Hawaii", Integer.valueOf(962));
/* 669 */     zoneid.put("Pacific/Johnston", Integer.valueOf(485));
/* 670 */     zoneid.put("Pacific/Kwajalein", Integer.valueOf(464));
/* 671 */     zoneid.put("Kwajalein", Integer.valueOf(976));
/* 672 */     zoneid.put("Pacific/Midway", Integer.valueOf(486));
/* 673 */     zoneid.put("Pacific/Samoa", Integer.valueOf(1502));
/* 674 */     zoneid.put("US/Samoa", Integer.valueOf(990));
/* 675 */     zoneid.put("Pacific/Yap", Integer.valueOf(978));
/* 676 */     zoneid.put("WET", Integer.valueOf(365));
    
/* 682 */     zoneid.putOld("EST", new Integer(1636));
/* 683 */     zoneid.putOld("UTC", new Integer(540));
/* 684 */     zoneid.putOld("MST", new Integer(2662));
/* 685 */     zoneid.putOld("HST", new Integer(1474));
/* 686 */     zoneid.putOld("CST6CDT", new Integer(1125));
/* 687 */     zoneid.putOld("MST7MDT", new Integer(2150));
/* 688 */     zoneid.putOld("PST8PDT", new Integer(1127));
/* 689 */     zoneid.putOld("EST5EDT", new Integer(1124));
  }
  
  public static int getID(String paramString)
  {
/* 701 */     int i = 0;
/* 702 */     Integer localInteger = zoneid.getID(paramString);
    
/* 706 */     if (localInteger == null) {
/* 707 */       i = -1;
    } else
/* 709 */       i = localInteger.intValue();
/* 710 */     return i;
  }
  
  public static String getRegion(int paramInt)
  {
/* 720 */     String str = zoneid.getZone(Integer.valueOf(paramInt));
    
/* 722 */     if (str == null)
    {
/* 728 */       str = zoneid.getOldZone(Integer.valueOf(paramInt));
    }
    
/* 731 */     return str;
  }
  
  public static boolean isValidID(int paramInt)
  {
/* 736 */     if (getRegion(paramInt) == null) {
/* 737 */       return false;
    }
/* 739 */     return true;
  }
  
  public static boolean isValidRegion(String paramString)
  {
/* 744 */     if (getID(paramString) == -1) {
/* 745 */       return false;
    }
/* 747 */     return true;
  }
}
/* Location:              /home/caixj/下载/ojdbc6.jar!/oracle/sql/ZONEIDMAP.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */